version: '3'
services:

  backend:
    build:
      context: ./Node
      dockerfile: Dockerfile
    image: node-backend
    container_name: node-backend
    hostname: backend_server
    volumes:
      - './Node/app:/var/www/app'
      - /var/www/app/node_modules
    tty: true
    depends_on:
      - mongo
    
  mongo:
    build: 
      context: ./MongoDB
      dockerfile: Dockerfile
    image: mongo-db
    container_name: mongo-db
    ports:
      - '${DB_PORT:-27017}:27017'
    volumes:
      - './MongoDB/data:/data'  
      - "./MongoDB/config/mongod.conf:/etc/mongod.conf"
      - "./MongoDB/log:/var/log/mongodb"
    restart: always

  frontend:
    build: 
      context: ./Vue
      dockerfile: Dockerfile
    image: vue-frontend
    container_name: vue-frontend
    volumes:
      - /app/node_modules
      - './Vue/app:/var/www/html'
    ports:
      - '${WEB_PORT:-8080}:8080'

  nginx: #build nginx cho backend
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: server-nginx
    container_name: server-nginx
    tty: true
    ports:
      - '${SERVER_PORT:-3002}:3002'
    depends_on:
      - backend