version: '3'
services:

  node:
    build:
      context: ./Node
      dockerfile: Dockerfile
    image: node-app
    ports:
      - '${APP_PORT:-3002}:3002'
    volumes:
      - './Node/app:/var/www/app'
      - /var/www/app/node_modules
    tty: true
    depends_on:
      - mongo
    
  mongo:
    build: 
      context: ./MongoDB
      dockerfile: Dockerfile
    image: mongo-db
    ports:
      - '${DB_PORT:-27017}:27017'
    volumes:
      - './MongoDB/data:/data'  
      - "./MongoDB/config/mongod.conf:/etc/mongod.conf"
      - "./MongoDB/log:/var/log/mongodb"
    restart: always
  
  # vue:
  #   build: 
  #     context: ./Vue
  #     dockerfile: Dockerfile
  #   image: todo/vue-web
  #   ports:
  #     - '${WEB_PORT:-8080}:8080'
  #   volumes:
  #     - '../web: /var/www/app'
    