version: '3'
services:

  # node:
  #   build:
  #     context: ./Node
  #     dockerfile: Dockerfile
  #   image: node-app
  #   container_name: node-app
  #   ports:
  #     - '${APP_PORT:-3002}:3002'
  #   volumes:
  #     - './Node/app:/var/www/app'
  #     - /var/www/app/node_modules
  #   tty: true
  #   depends_on:
  #     - mongo
    
  # mongo:
  #   build: 
  #     context: ./MongoDB
  #     dockerfile: Dockerfile
  #   image: mongo-db
  #   container_name: mongo-db
  #   ports:
  #     - '${DB_PORT:-27017}:27017'
  #   volumes:
  #     - './MongoDB/data:/data'  
  #     - "./MongoDB/config/mongod.conf:/etc/mongod.conf"
  #     - "./MongoDB/log:/var/log/mongodb"
  #   restart: always
  
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-todo
    container_name: nginx-todo
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Vue/app:/var/www/html
    ports:
      - '${WEB_PORT:-8080}:80'
    depends_on:
      - vue

  vue:
    build: 
      context: ./Vue
      dockerfile: Dockerfile
    image: vue-web
    container_name: vue-web
    # ports:
    #   - '${APP_PORT:-8080}:80'
    volumes:
      - './Vue/app:/var/www/html'
      # - /var/www/app/node_modules
    