version: '3'
services:

  node:
    build:
      context: ./Node
      dockerfile: Dockerfile
    image: todo/node-app
    ports:
      - '${APP_PORT:-8082}:8082'
    volumes:
      - '../app:/var/www/app'
    tty: true
    
  mongo:
    build: 
      context: ./MongoDB
      dockerfile: Dockerfile
    image: todo/mongo-db
    ports:
      - '${DB_PORT:-28017}:27017'
    volumes:
      - '../data: /data/db'
  
  vue:
    build: 
      context: ./Vue
      dockerfile: Dockerfile
    image: todo/vue-web
    ports:
      - '${WEB_PORT:-8080}:8080'
    volumes:
      - '../web: /var/www/app'
    