FROM nginx:stable-alpine

LABEL maintainer="tuandd99.nta@gmail.com" 

# RUN  apt-get -y update && apt-get -y install nginx

# COPY nginx.conf /etc/nginx/conf.d/default.conf

# COPY ~/Vue/app /var/www/html

# WORKDIR /app/dist

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]